import { ApiProperty } from '@nestjs/swagger';

export class TopProductResponseDto {
  @ApiProperty({
    description: 'Product unique identifier.',
    example: '8f42f0a6-1464-47db-bef9-7e8cb2d6144d',
  })
  productId: string;

  @ApiProperty({
    description: 'Product display name.',
    example: 'Cheeseburger',
  })
  productName: string;

  @ApiProperty({
    description: 'Total quantity sold in the selected period.',
    example: 37,
  })
  quantitySold: number;

  @ApiProperty({
    description:
      'Total sales amount generated by this product in the selected period.',
    example: 1098.63,
  })
  totalSales: number;
}
