/* eslint-disable */
export default async () => {
    const t = {
        ["./auth/dto/user-response.dto"]: await import("./auth/dto/user-response.dto"),
        ["./auth/models/token.model"]: await import("./auth/models/token.model"),
        ["./staff/dto/staff-response.dto"]: await import("./staff/dto/staff-response.dto"),
        ["./staff/dto/staff-invite-response.dto"]: await import("./staff/dto/staff-invite-response.dto"),
        ["./staff/dto/staff-list-item.dto"]: await import("./staff/dto/staff-list-item.dto")
    };
    return { "@nestjs/swagger/plugin": { "models": [[import("./auth/dto/user-response.dto"), { "UserTenantRoleDto": { tenantId: { required: true, type: () => String }, role: { required: true, type: () => Object } }, "UserResponseDto": { id: { required: true, type: () => String }, name: { required: true, type: () => String }, email: { required: true, type: () => String }, isActive: { required: true, type: () => Boolean }, tenantRoles: { required: true, type: () => [t["./auth/dto/user-response.dto"].UserTenantRoleDto] }, createdAt: { required: true, type: () => Date }, updatedAt: { required: true, type: () => Date } } }], [import("./staff/dto/staff-invite-response.dto"), { "StaffInviteResponseDto": { id: { required: true, type: () => String }, email: { required: true, type: () => String }, tenantId: { required: true, type: () => String }, unitId: { required: true, type: () => String }, role: { required: true, type: () => Object }, status: { required: true, type: () => String }, inviteToken: { required: true, type: () => String }, expiresAt: { required: true, type: () => Date } } }], [import("./staff/dto/staff-list-item.dto"), { "StaffListItemDto": { userId: { required: true, type: () => String }, name: { required: true, type: () => String }, email: { required: true, type: () => String }, isActive: { required: true, type: () => Boolean }, tenantRoles: { required: true, type: () => [Object] } } }], [import("./staff/dto/staff-response.dto"), { "StaffResponseDto": { userId: { required: true, type: () => String }, name: { required: true, type: () => String }, email: { required: true, type: () => String }, tenantId: { required: true, type: () => String }, unitId: { required: true, type: () => String }, role: { required: true, type: () => Object }, isNewUser: { required: true, type: () => Boolean } } }], [import("./common/pagination/pagination.dto"), { "PaginationDto": { page: { required: false, type: () => Number, default: 1, minimum: 1 }, limit: { required: false, type: () => Number, default: 10, minimum: 1 } } }]], "controllers": [[import("./app.controller"), { "AppController": { "getHealth": {} } }], [import("./auth/auth.controller"), { "AuthController": { "signup": { type: t["./auth/models/token.model"].Token }, "login": { type: t["./auth/models/token.model"].Token }, "refresh": { type: t["./auth/models/token.model"].Token }, "me": { type: Object } } }], [import("./staff/staff.controller"), { "StaffController": { "createStaff": { type: t["./staff/dto/staff-response.dto"].StaffResponseDto }, "inviteStaff": { type: t["./staff/dto/staff-invite-response.dto"].StaffInviteResponseDto }, "acceptInvite": { type: t["./staff/dto/staff-response.dto"].StaffResponseDto }, "listStaff": { type: [t["./staff/dto/staff-list-item.dto"].StaffListItemDto] }, "updateStaffStatus": { type: t["./staff/dto/staff-list-item.dto"].StaffListItemDto } } }]] } };
};